/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: zetxune (https://sketchfab.com/zetxune)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/the-weaver-v2-rigged-553ea1808c8346e8ac90f04285c63e54
title: "The Weaver" (V2, Rigged)
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/useGLTF'

import { useAnimations } from '@react-three/drei/useAnimations'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/assets/rigged/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes._rootJoint} />
          <group position={[0, -2.13, 4.48]} scale={[25.28, 25.28, 25.28]} />
          <skinnedMesh
            material={materials.weapons_material}
            geometry={nodes.bat_weapons_material_0.geometry}
            skeleton={nodes.bat_weapons_material_0.skeleton}
          />
          <skinnedMesh
            material={materials.weaver_material}
            geometry={nodes.holster_bat_weaver_material_0.geometry}
            skeleton={nodes.holster_bat_weaver_material_0.skeleton}
          />
          <skinnedMesh
            material={materials.weaver_material}
            geometry={nodes.lefteye_weaver_material_0.geometry}
            skeleton={nodes.lefteye_weaver_material_0.skeleton}
          />
          <skinnedMesh
            material={materials.weaver_material}
            geometry={nodes.righteye_weaver_material_0.geometry}
            skeleton={nodes.righteye_weaver_material_0.skeleton}
          />
          <skinnedMesh
            material={materials.weaver_material}
            geometry={nodes.weaver_weaver_material_0.geometry}
            skeleton={nodes.weaver_weaver_material_0.skeleton}
          />
          <skinnedMesh
            material={materials.weaver_material}
            geometry={nodes.weaver_ponytail_weaver_material_0.geometry}
            skeleton={nodes.weaver_ponytail_weaver_material_0.skeleton}
          />
          <skinnedMesh
            material={materials.powers}
            geometry={nodes.powers_effect_powers_0.geometry}
            skeleton={nodes.powers_effect_powers_0.skeleton}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/rigged/scene.gltf')
